package-lock.json, package.json, scripts/create-dummy-assets.js
Hi,
This PR adds a script to create dummy assets to test some functionality while waiting for the real assets.
=> Create dummy assets

.env.example, bin/start-ipfs-local-node.sh, bin/start-local-ipfs-node.sh, config/index.js, ipfs/index.js, ipfs/utils.js, package-lock.json, package.json, scripts/bot.js, scripts/create-dummy-assets.js
This PR includes:
- Script to run a local ipfs node
- IPFS module to interact with local ipfs node and pinning service.
- Some clean ups.
=> Scaffold for ipfs

.gitignore, contracts/Ethernauts.sol, hardhat.config.js, test/General.test.js, test/Mint.test.js, test/Withdraw.test.js
=> Simplify contract to mvp

contracts/Ethernauts.sol, test/Mint.test.js
=> Reserve tokens for gifting

.gitignore, hardhat.config.js, package-lock.json, package.json
=> Add Solidity coverage

.eslintignore, .github/workflows/ci.yml, .prettierignore
=> Added CI build

packages/hardhat/contracts/Ethernauts.sol, packages/hardhat/test/Random.test.js
=> Implemented simplified random number generation method

packages/hardhat/contracts/Ethernauts.sol, packages/hardhat/test/Random.test.js
=> Try to generate a random number when minting an nft

package-lock.json, packages/dapp/components/Buttons/ConnectWallet/ConnectWallet.js, packages/dapp/components/Buttons/ConnectWallet/ConnectWallet.module.scss, packages/dapp/components/Buttons/Mint/Mint.js, packages/dapp/components/DonationSlide/DonationSlide.js, packages/dapp/components/DonationSlide/DonationSlide.module.scss, packages/dapp/components/DonationSlide/index.js, packages/dapp/components/Header/Header.js, packages/dapp/components/Header/Header.module.scss, packages/dapp/components/Layout/Layout.module.scss, packages/dapp/components/WalletInfo/WalletInfo.module.scss, packages/dapp/constants.js, packages/dapp/contexts/DonationProvider/DonationProvider.js, packages/dapp/contexts/DonationProvider/index.js, packages/dapp/hooks/useEarlyMint.js, packages/dapp/hooks/useMint.js, packages/dapp/hooks/useSaleState.js, packages/dapp/package.json, packages/dapp/pages/_app.js, packages/dapp/pages/index.js, packages/dapp/pages/index.module.scss, packages/dapp/styles/breakpoints.scss, packages/dapp/styles/globals.scss, packages/dapp/styles/rc-slider.scss
Closes #120 
https://user-images.githubusercontent.com/15804684/142918056-cab230ae-917a-44dd-ae4a-ce10a1095256.mov
=> Add responsive html structure to the mint page

README.md, docker/development.docker-compose.yml, docker/hardhat.Dockerfile, package-lock.json, package.json, packages/dapp/components/Buttons/ConnectWallet/ConnectWallet.js, packages/dapp/components/Buttons/ConnectWallet/ConnectWallet.module.scss, packages/dapp/components/Buttons/Mint/Mint.js, packages/dapp/components/DonationSlide/DonationSlide.js, packages/dapp/components/DonationSlide/DonationSlide.module.scss, packages/dapp/components/DonationSlide/index.js, packages/dapp/components/Header/Header.js, packages/dapp/components/Header/Header.module.scss, packages/dapp/components/Layout/Layout.module.scss, packages/dapp/components/WalletInfo/WalletInfo.module.scss, packages/dapp/constants.js, packages/dapp/contexts/DonationProvider/DonationProvider.js, packages/dapp/contexts/DonationProvider/index.js, packages/dapp/hooks/useEarlyMint.js, packages/dapp/hooks/useMint.js, packages/dapp/hooks/useSaleState.js, packages/dapp/package.json, packages/dapp/pages/_app.js, packages/dapp/pages/index.js, packages/dapp/pages/index.module.scss, packages/dapp/styles/breakpoints.scss, packages/dapp/styles/globals.scss, packages/dapp/styles/rc-slider.scss, packages/hardhat/package.json
=> Fix docker compose commands and improve readme

package-lock.json, packages/keeper/contracts/Ethernauts.sol, packages/keeper/hardhat.config.js, packages/keeper/package.json, packages/keeper/scripts/jobs.js, packages/keeper/scripts/queue.js, packages/keeper/scripts/upload-resource.js, packages/keeper/src/config.js, packages/keeper/src/parse-mint.js, packages/keeper/src/process-mint.js, packages/keeper/test/src/parse-mint.test.js
=> Add assets upload to ipfs

packages/dapp/components/AvailableSupply/AvailableSupply.js, packages/dapp/components/AvailableSupply/AvailableSupply.module.scss, packages/dapp/components/Gallery/Gallery.js, packages/dapp/components/Mint/Mint.js, packages/dapp/components/Mint/Mint.module.scss, packages/dapp/hooks/useGallery.js, packages/dapp/styles/theme.scss
Hi,
This PR adds the available supply at the bottom of the mint button
=> Add available supply

README.md, docker-compose.yml, packages/hardhat/hardhat.config.js, packages/hardhat/tasks/exec.js, packages/keeper/src/process-jobs.js
=> Add base url update

packages/hardhat/.solcover.js, packages/hardhat/contracts/Ethernauts.sol, packages/hardhat/test/Mint.test.js, packages/hardhat/test/State.test.js
=> Increase coverage to 100%

docker/production.docker-compose.yml, package-lock.json, packages/keeper/.gitignore, packages/keeper/package.json, packages/keeper/scripts/events.js, packages/keeper/scripts/queue.js, packages/keeper/scripts/worker.js, packages/keeper/src/config.js, packages/keeper/src/errors-catch.js, packages/keeper/src/errors-report.js, packages/keeper/src/notify.js, packages/keeper/src/process-jobs.js
Closes #95 
Includes:
* Dumps node apps crashes to a file, and before restarting the server, reports the dump file to Discord
* Reports main queue events to Discord
* Some refactors on production compose file
=> Add discord error & events reporting

docker-compose.yml, docker/dapp.Dockerfile, packages/hardhat/hardhat.config.js, packages/hardhat/tasks/deploy.js, packages/keeper/hardhat.config.js
=> Fix default compose configuration

packages/dapp/hooks/useGallery.js
Closes #238 
This PR fixes the amount of requests to the blockchain by locally calculating if a given `tokenId` is already revealed instead of asking the contract.
=> Fix gallery rendering - too many requests to blockchain

packages/dapp/components/Mint/Mint.module.scss
=> Prevent image from stretching in mobile

packages/dapp/components/AvailableToMint/AvailableToMint.js, packages/dapp/components/AvailableToMint/AvailableToMint.module.scss, packages/dapp/components/Buttons/ConnectWallet/ConnectWallet.js, packages/dapp/components/Buttons/Mint/EarlyMint/EarlyMint.js, packages/dapp/components/Buttons/Mint/OpenMint/OpenMint.js, packages/dapp/components/Mint/Mint.js, packages/dapp/components/Mint/Mint.module.scss, packages/dapp/components/Toast/Toast.js, packages/dapp/components/WalletInfo/WalletInfo.js, packages/dapp/hooks/useAvailableToMint.js
=> Fix multiple calls to the rpc provider

package-lock.json, package.json, packages/dapp/components/Buttons/Mint/EarlyMint/EarlyMint.js, packages/dapp/contexts/WalletProvider/WalletProvider.js, packages/dapp/hooks/useEarlyMint.js, packages/dapp/hooks/useIsWindowFocused.js, packages/dapp/hooks/useSwitchNetwork.js, packages/dapp/package.json
This PR adds the ability to use Wallet Connect and Metamask to connect wallets.
=> Wallet Improvements

README.md, packages/keeper/scripts/process-batch.js, packages/keeper/src/process-jobs.js
This PR implements the fix necessary for the Keepers upload of assets mentioned here as Option#1: https://www.notion.so/EthernautDAO-Asset-Upload-Fix-cf8511c14ddb4c83b20af2a222b97008
It also adds a new script to be able to reprocess the already finished batch `0`;
=> Fix assets upload

packages/keeper/src/constants.js, packages/keeper/src/process-jobs.js
=> After a batch ends, check several times for baseURI update
